### ISSUE TITLE
Dataset files are missing during training

### ISSUE THREAD

**Issue by yuangan** [NVlabs/GOHA#1]
Hi, it looks like these dataset files are missing in ```src/dataset```. Could you please provide these files for training? Thank you for your great work.
![image](https://github.com/NVlabs/GOHA/assets/12268263/10642b57-3152-4d5a-b253-bdba20ed8840)

**Comment by Johnren1111** [comment]
I find the same problem. Do you have fixed it?

**Comment by yuangan** [comment]
No, I think they are waiting for us to implement them. :disappointed_relieved:

**Comment by sunshineatnoon** [comment]
Please see https://github.com/NVlabs/GOHA/issues/7
