### ISSUE TITLE
missing std_exp.txt

### ISSUE THREAD

**Issue by JackAILab** [NVlabs/GOHA#6]
raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: ../external/BFM/std_exp.txt not found.

![image](https://github.com/NVlabs/GOHA/assets/112920087/bfbbd17b-660e-4176-ac34-788cc6bc324c)

How can I get this file, I followed the [Deep3DFaceRecon_pytorch](https://github.com/sicxu/Deep3DFaceRecon_pytorch), no other files can be found here

**Comment by Vanessik** [comment]
https://github.com/sicxu/Deep3DFaceRecon_pytorch/tree/master/BFM check here
