### ISSUE TITLE
Training files are missing

### ISSUE THREAD

**Issue by berkegokmen1** [NVlabs/GOHA#7]
Hi,

Could you please share the training files shown in the screenshot below? Or could you tell where to find them? We cannot run the training without those.

Thanks in advance.

<img width="819" alt="Screenshot 2024-09-12 at 11 11 38" src="https://github.com/user-attachments/assets/aab33ef8-f3df-4663-907a-0729b2e85f96">

**Comment by sunshineatnoon** [comment]
[training_files.zip](https://github.com/user-attachments/files/17334904/training_files.zip)
